""" @Author: Milan Biranwar @Date: 15-11-2022 02:00PM @Last Modified by: Milan Biranwar @Last Modified time: 15-11-2022 03:00AM @Title : NumPy Problems """


1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [8]:
import numpy as np
arr =  [12.23, 13.32, 100, 36.32]
numpy_arr = np.array(arr)
print("one dimentinal numpy array is ",numpy_arr)

one dimentinal numpy array is :  [ 12.23  13.32 100.    36.32]


2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [17]:
a = np.arange(2,11)
b = a.reshape(3,3)
print("3x3 matrix with values ranging from 2 to 10 is ",b)



3x3 matrix with values ranging from 2 to 10 is  [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]


In [18]:
a = np.zeros(10)
a[6] = 11
print(" Updated sixth index value of array a with 11 is ",a)


 Updated sixth index value of array a with 11 is  [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [11]:
a = np.arange(12, 38)
print("Original array is ", a)

b = a[:: -1]
print("Reversed array is ", b)

Original array is  [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reversed array is  [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]
